//void shiftByte(byte v);
void setStCpPin(int newPin);
int getStCpPin();
void setShCpPin(int newPin);
int getShCpPin();
void setRelay(int relayNum, bool state);
void relayOff();
void relayOn();
void setDsCpPin(int newPin);
int getDsCpPin();
